version: "3.8"

services:
  mysql:
    image: mysql:latest
    container_name: fanta-container
    environment:
      MYSQL_ROOT_PASSWORD: supremoBoss123
      MYSQL_DATABASE: app_fantacalcio
      MYSQL_USER: davide
      MYSQL_PASSWORD: davide123
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - my-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: fantacalcio-container
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: davide
      PMA_PASSWORD: davide123
    ports:
      - "8080:80"
    networks:
      - my-network

volumes:
  mysql-data:

networks:
  my-network:
